-- Auto-genereret af db/build-seed.mjs. Rediger ikke i hånden.
DELETE FROM employees;
DELETE FROM areas;
DELETE FROM roles;
DELETE FROM constraints;
DELETE FROM config;

INSERT INTO employees (id, name, birthdate, max_hours_per_week, max_hours_per_day, min_hours_per_week, employment_type, roles, availability, preferences, absences) VALUES ('emp_1', 'Anna Berg', '1990-04-12', 37, 8, 30, 'fuldtid', '["kasseansvarlig","kasse"]', '[{"day":"monday","start":"09:00","end":"17:00"},{"day":"tuesday","start":"09:00","end":"17:00"},{"day":"wednesday","start":"09:00","end":"17:00"},{"day":"thursday","start":"09:00","end":"17:00"},{"day":"friday","start":"09:00","end":"17:00"}]', '[{"day":"friday","start":"09:00","end":"13:00","kind":"prefer","weight":2}]', '[]');
INSERT INTO employees (id, name, birthdate, max_hours_per_week, max_hours_per_day, min_hours_per_week, employment_type, roles, availability, preferences, absences) VALUES ('emp_2', 'Bo Dahl', '1988-09-01', 37, 8, 30, 'fuldtid', '["lukkeansvarlig","kasse"]', '[{"day":"monday","start":"12:00","end":"20:00"},{"day":"tuesday","start":"12:00","end":"20:00"},{"day":"wednesday","start":"12:00","end":"20:00"},{"day":"thursday","start":"12:00","end":"20:00"},{"day":"friday","start":"12:00","end":"20:00"}]', '[]', '[]');
INSERT INTO employees (id, name, birthdate, max_hours_per_week, max_hours_per_day, min_hours_per_week, employment_type, roles, availability, preferences, absences) VALUES ('emp_3', 'Clara Eg', '1995-02-20', 30, 8, 20, 'deltid', '["drivhus"]', '[{"day":"monday","start":"09:00","end":"16:00"},{"day":"tuesday","start":"09:00","end":"16:00"},{"day":"wednesday","start":"09:00","end":"16:00"},{"day":"thursday","start":"09:00","end":"16:00"},{"day":"friday","start":"09:00","end":"16:00"}]', '[]', '[{"from":"2026-06-22","to":"2026-06-28","kind":"vacation","note":"Ferie"}]');
INSERT INTO employees (id, name, birthdate, max_hours_per_week, max_hours_per_day, min_hours_per_week, employment_type, roles, availability, preferences, absences) VALUES ('emp_4', 'David Friis', '1999-11-05', 37, 8, 30, 'fuldtid', '["hal"]', '[{"day":"monday","start":"09:00","end":"18:00"},{"day":"tuesday","start":"09:00","end":"18:00"},{"day":"wednesday","start":"09:00","end":"18:00"},{"day":"thursday","start":"09:00","end":"18:00"},{"day":"saturday","start":"09:00","end":"18:00"}]', '[]', '[]');
INSERT INTO employees (id, name, birthdate, max_hours_per_week, max_hours_per_day, min_hours_per_week, employment_type, roles, availability, preferences, absences) VALUES ('emp_5', 'Emma Holm', '2009-03-15', 12, 6, 0, 'ungarbejder', '["kasse"]', '[{"day":"monday","start":"15:00","end":"20:00"},{"day":"wednesday","start":"15:00","end":"20:00"},{"day":"saturday","start":"09:00","end":"15:00"}]', '[]', '[]');
INSERT INTO employees (id, name, birthdate, max_hours_per_week, max_hours_per_day, min_hours_per_week, employment_type, roles, availability, preferences, absences) VALUES ('emp_6', 'Frederik Lund', '2008-08-22', 15, 7, 0, 'ungarbejder', '["hal","lager"]', '[{"day":"monday","start":"15:00","end":"20:00"},{"day":"wednesday","start":"15:00","end":"20:00"},{"day":"friday","start":"15:00","end":"20:00"},{"day":"saturday","start":"09:00","end":"18:00"}]', '[]', '[]');
INSERT INTO employees (id, name, birthdate, max_hours_per_week, max_hours_per_day, min_hours_per_week, employment_type, roles, availability, preferences, absences) VALUES ('emp_7', 'Gitte Mark', '1985-07-30', 37, 8, 30, 'fuldtid', '["kasseansvarlig","lukkeansvarlig"]', '[{"day":"monday","start":"11:00","end":"20:00"},{"day":"tuesday","start":"11:00","end":"20:00"},{"day":"wednesday","start":"11:00","end":"20:00"},{"day":"thursday","start":"11:00","end":"20:00"},{"day":"friday","start":"11:00","end":"20:00"}]', '[]', '[]');
INSERT INTO employees (id, name, birthdate, max_hours_per_week, max_hours_per_day, min_hours_per_week, employment_type, roles, availability, preferences, absences) VALUES ('emp_8', 'Hassan Nør', '1992-12-12', 37, 8, 30, 'fuldtid', '["drivhus","lager"]', '[{"day":"tuesday","start":"09:00","end":"18:00"},{"day":"wednesday","start":"09:00","end":"18:00"},{"day":"thursday","start":"09:00","end":"18:00"},{"day":"friday","start":"09:00","end":"18:00"},{"day":"saturday","start":"09:00","end":"18:00"}]', '[]', '[]');
INSERT INTO employees (id, name, birthdate, max_hours_per_week, max_hours_per_day, min_hours_per_week, employment_type, roles, availability, preferences, absences) VALUES ('emp_9', 'Ida Pil', '2009-05-05', 12, 6, 0, 'ungarbejder', '["kasse"]', '[{"day":"tuesday","start":"15:00","end":"20:00"},{"day":"thursday","start":"15:00","end":"20:00"},{"day":"sunday","start":"10:00","end":"16:00"}]', '[]', '[]');
INSERT INTO employees (id, name, birthdate, max_hours_per_week, max_hours_per_day, min_hours_per_week, employment_type, roles, availability, preferences, absences) VALUES ('emp_10', 'Jens Roan', '1997-01-19', 37, 8, 30, 'fuldtid', '["hal"]', '[{"day":"tuesday","start":"09:00","end":"18:00"},{"day":"wednesday","start":"09:00","end":"18:00"},{"day":"thursday","start":"09:00","end":"18:00"},{"day":"friday","start":"09:00","end":"18:00"},{"day":"saturday","start":"09:00","end":"18:00"}]', '[]', '[]');
INSERT INTO employees (id, name, birthdate, max_hours_per_week, max_hours_per_day, min_hours_per_week, employment_type, roles, availability, preferences, absences) VALUES ('emp_11', 'Karen Storm', '1980-10-10', 25, 8, 15, 'deltid', '["drivhus"]', '[{"day":"monday","start":"09:00","end":"16:00"},{"day":"tuesday","start":"09:00","end":"16:00"},{"day":"wednesday","start":"09:00","end":"16:00"},{"day":"thursday","start":"09:00","end":"16:00"}]', '[]', '[]');
INSERT INTO employees (id, name, birthdate, max_hours_per_week, max_hours_per_day, min_hours_per_week, employment_type, roles, availability, preferences, absences) VALUES ('emp_12', 'Lars Vinter', '2006-02-02', 30, 8, 20, 'deltid', '["lager","hal"]', '[{"day":"monday","start":"09:00","end":"15:00"},{"day":"tuesday","start":"09:00","end":"15:00"},{"day":"wednesday","start":"09:00","end":"15:00"},{"day":"thursday","start":"09:00","end":"15:00"},{"day":"friday","start":"09:00","end":"15:00"}]', '[]', '[]');

INSERT INTO areas (id, name, roles, default_min_staff, min_staff_rules) VALUES ('kasse', 'Kasse', '["kasse","kasseansvarlig"]', 2, '{}');
INSERT INTO areas (id, name, roles, default_min_staff, min_staff_rules) VALUES ('drivhus', 'Drivhus', '["drivhus"]', 2, '{}');
INSERT INTO areas (id, name, roles, default_min_staff, min_staff_rules) VALUES ('hal_1', 'Hal 1', '["hal"]', 2, '{}');
INSERT INTO areas (id, name, roles, default_min_staff, min_staff_rules) VALUES ('lager', 'Lager', '["lager"]', 1, '{}');

INSERT INTO roles (id, name) VALUES ('kasse', 'Kasse');
INSERT INTO roles (id, name) VALUES ('kasseansvarlig', 'Kasseansvarlig');
INSERT INTO roles (id, name) VALUES ('drivhus', 'Drivhus');
INSERT INTO roles (id, name) VALUES ('hal', 'Hal');
INSERT INTO roles (id, name) VALUES ('lager', 'Lager');
INSERT INTO roles (id, name) VALUES ('lukkeansvarlig', 'Lukkeansvarlig');

INSERT INTO constraints (id, data) VALUES ('kasse_bemanding', '{"id":"kasse_bemanding","type":"staffing","area":"kasse","description":"Kasse: mindst 2, heraf mindst 1 over 18 og mindst 1 kasseansvarlig","days":["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],"time_from":"09:00","time_to":"20:00","min_total":2,"requirements":[{"count":1,"min_age":18},{"count":1,"role":"kasseansvarlig"}]}');
INSERT INTO constraints (id, data) VALUES ('drivhus_dag', '{"id":"drivhus_dag","type":"staffing","area":"drivhus","description":"Drivhus: mindst 2 i dagtimerne","days":["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],"time_from":"09:00","time_to":"18:00","min_total":2}');
INSERT INTO constraints (id, data) VALUES ('drivhus_foer_luk', '{"id":"drivhus_foer_luk","type":"staffing","area":"drivhus","description":"Drivhus: højst 1 de sidste 2 timer før luk","days":["monday","tuesday","wednesday","thursday","friday"],"relative":{"anchor":"close","from_offset_min":-120,"to_offset_min":0},"max_total":1}');
INSERT INTO constraints (id, data) VALUES ('hal1_bemanding', '{"id":"hal1_bemanding","type":"staffing","area":"hal_1","description":"Hal 1: mindst 2 hele dagen","days":["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],"time_from":"09:00","time_to":"20:00","min_total":2}');
INSERT INTO constraints (id, data) VALUES ('lager_formiddag', '{"id":"lager_formiddag","type":"staffing","area":"lager","description":"Lager: mindst 1 om formiddagen","days":["monday","tuesday","wednesday","thursday","friday"],"time_from":"09:00","time_to":"15:00","min_total":1}');

INSERT INTO config (key, value) VALUES ('global', '{"opening_hours":{"monday":{"from":"09:00","to":"20:00"},"tuesday":{"from":"09:00","to":"20:00"},"wednesday":{"from":"09:00","to":"20:00"},"thursday":{"from":"09:00","to":"20:00"},"friday":{"from":"09:00","to":"20:00"},"saturday":{"from":"09:00","to":"18:00"},"sunday":{"from":"10:00","to":"16:00"}},"time_slot_minutes":60,"defaults":{"max_hours_per_week":37,"max_hours_per_day":8},"planning":{"max_consecutive_days":6,"min_rest_hours_between_days":11},"closing":{"require_closing_responsible":true,"closing_role":"lukkeansvarlig"},"weekend_days":["saturday","sunday"]}');
