-- Auto-genereret af db/build-seed.mjs. Rediger ikke i hånden.
DELETE FROM employees;
DELETE FROM areas;
DELETE FROM roles;
DELETE FROM constraints;
DELETE FROM config;

INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_1', 'Anna', 36, 8, '["lukkeansvarlig","kasse"]', '[{"day":"monday","start":"11:00","end":"19:00"},{"day":"tuesday","start":"11:00","end":"19:00"},{"day":"wednesday","start":"11:00","end":"19:00"},{"day":"thursday","start":"11:00","end":"19:00"},{"day":"friday","start":"11:00","end":"19:00"},{"day":"saturday","start":"11:00","end":"19:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_2', 'Bo', 32, 8, '["lager"]', '[{"day":"monday","start":"07:00","end":"15:00"},{"day":"tuesday","start":"07:00","end":"15:00"},{"day":"wednesday","start":"07:00","end":"15:00"},{"day":"thursday","start":"07:00","end":"15:00"},{"day":"friday","start":"07:00","end":"15:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_3', 'Clara', 24, 8, '["kasse","have"]', '[{"day":"monday","start":"11:00","end":"19:00"},{"day":"tuesday","start":"11:00","end":"19:00"},{"day":"wednesday","start":"11:00","end":"19:00"},{"day":"thursday","start":"11:00","end":"19:00"},{"day":"sunday","start":"07:00","end":"15:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_4', 'David', 36, 8, '["lukkeansvarlig","lager"]', '[{"day":"monday","start":"11:00","end":"19:00"},{"day":"tuesday","start":"11:00","end":"19:00"},{"day":"wednesday","start":"11:00","end":"19:00"},{"day":"thursday","start":"11:00","end":"19:00"},{"day":"friday","start":"11:00","end":"19:00"},{"day":"saturday","start":"07:00","end":"15:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_5', 'Erik', 20, 6, '["lager"]', '[{"day":"monday","start":"15:00","end":"19:00"},{"day":"tuesday","start":"15:00","end":"19:00"},{"day":"wednesday","start":"15:00","end":"19:00"},{"day":"thursday","start":"15:00","end":"19:00"},{"day":"saturday","start":"11:00","end":"19:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_6', 'Freja', 16, 6, '["kasse"]', '[{"day":"monday","start":"15:00","end":"19:00"},{"day":"tuesday","start":"15:00","end":"19:00"},{"day":"wednesday","start":"15:00","end":"19:00"},{"day":"thursday","start":"15:00","end":"19:00"},{"day":"sunday","start":"11:00","end":"19:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_7', 'Gustav', 28, 8, '["have"]', '[{"day":"tuesday","start":"07:00","end":"15:00"},{"day":"wednesday","start":"07:00","end":"15:00"},{"day":"thursday","start":"07:00","end":"15:00"},{"day":"friday","start":"07:00","end":"15:00"},{"day":"saturday","start":"07:00","end":"15:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_8', 'Helena', 36, 8, '["kasse","lager"]', '[{"day":"monday","start":"07:00","end":"15:00"},{"day":"tuesday","start":"07:00","end":"15:00"},{"day":"wednesday","start":"07:00","end":"15:00"},{"day":"thursday","start":"07:00","end":"15:00"},{"day":"friday","start":"07:00","end":"15:00"},{"day":"sunday","start":"07:00","end":"15:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_9', 'Ida', 36, 8, '["lukkeansvarlig","kasse"]', '[{"day":"monday","start":"11:00","end":"19:00"},{"day":"tuesday","start":"11:00","end":"19:00"},{"day":"wednesday","start":"11:00","end":"19:00"},{"day":"thursday","start":"11:00","end":"19:00"},{"day":"friday","start":"11:00","end":"19:00"},{"day":"saturday","start":"11:00","end":"19:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_10', 'Jonas', 24, 6, '["lager"]', '[{"day":"monday","start":"15:00","end":"19:00"},{"day":"tuesday","start":"15:00","end":"19:00"},{"day":"wednesday","start":"15:00","end":"19:00"},{"day":"thursday","start":"15:00","end":"19:00"},{"day":"saturday","start":"11:00","end":"19:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_11', 'Karina', 24, 8, '["kasse"]', '[{"day":"monday","start":"07:00","end":"15:00"},{"day":"tuesday","start":"07:00","end":"15:00"},{"day":"wednesday","start":"07:00","end":"15:00"},{"day":"friday","start":"07:00","end":"15:00"},{"day":"saturday","start":"07:00","end":"15:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_12', 'Lars', 32, 8, '["have","lager"]', '[{"day":"monday","start":"07:00","end":"15:00"},{"day":"tuesday","start":"07:00","end":"15:00"},{"day":"wednesday","start":"07:00","end":"15:00"},{"day":"thursday","start":"07:00","end":"15:00"},{"day":"friday","start":"07:00","end":"15:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_13', 'Maja', 28, 8, '["kasse","lukkeansvarlig"]', '[{"day":"thursday","start":"11:00","end":"19:00"},{"day":"friday","start":"11:00","end":"19:00"},{"day":"saturday","start":"11:00","end":"19:00"},{"day":"sunday","start":"11:00","end":"19:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_14', 'Nicolai', 20, 6, '["lager"]', '[{"day":"friday","start":"15:00","end":"19:00"},{"day":"saturday","start":"07:00","end":"19:00"},{"day":"sunday","start":"07:00","end":"19:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_15', 'Olivia', 16, 6, '["have"]', '[{"day":"wednesday","start":"15:00","end":"19:00"},{"day":"saturday","start":"07:00","end":"19:00"},{"day":"sunday","start":"07:00","end":"19:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_16', 'Patrick', 32, 8, '["lukkeansvarlig","lager"]', '[{"day":"thursday","start":"11:00","end":"19:00"},{"day":"friday","start":"11:00","end":"19:00"},{"day":"saturday","start":"11:00","end":"19:00"},{"day":"sunday","start":"11:00","end":"19:00"},{"day":"monday","start":"11:00","end":"19:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_17', 'Rikke', 20, 6, '["kasse"]', '[{"day":"monday","start":"15:00","end":"19:00"},{"day":"tuesday","start":"15:00","end":"19:00"},{"day":"wednesday","start":"15:00","end":"19:00"},{"day":"thursday","start":"15:00","end":"19:00"},{"day":"saturday","start":"11:00","end":"19:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_18', 'Simon', 36, 8, '["lager","have"]', '[{"day":"monday","start":"07:00","end":"15:00"},{"day":"tuesday","start":"07:00","end":"15:00"},{"day":"wednesday","start":"07:00","end":"15:00"},{"day":"thursday","start":"07:00","end":"15:00"},{"day":"friday","start":"07:00","end":"15:00"},{"day":"saturday","start":"11:00","end":"19:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_19', 'Tina', 28, 8, '["kasse"]', '[{"day":"tuesday","start":"11:00","end":"19:00"},{"day":"wednesday","start":"11:00","end":"19:00"},{"day":"thursday","start":"11:00","end":"19:00"},{"day":"friday","start":"11:00","end":"19:00"},{"day":"saturday","start":"11:00","end":"19:00"}]');
INSERT INTO employees (id, name, max_hours_per_week, max_hours_per_day, roles, availability) VALUES ('emp_20', 'Uffe', 36, 8, '["lukkeansvarlig","kasse"]', '[{"day":"monday","start":"11:00","end":"19:00"},{"day":"tuesday","start":"11:00","end":"19:00"},{"day":"wednesday","start":"11:00","end":"19:00"},{"day":"thursday","start":"11:00","end":"19:00"},{"day":"friday","start":"11:00","end":"19:00"},{"day":"sunday","start":"11:00","end":"19:00"}]');

INSERT INTO areas (id, name, roles, default_min_staff, min_staff_rules) VALUES ('kasse', 'Kasse', '["kasse","lukkeansvarlig"]', 3, '{}');
INSERT INTO areas (id, name, roles, default_min_staff, min_staff_rules) VALUES ('bolig', 'Bolig', '["lager"]', 3, '{}');
INSERT INTO areas (id, name, roles, default_min_staff, min_staff_rules) VALUES ('have', 'Have', '["have"]', 1, '{}');

INSERT INTO roles (id, name) VALUES ('lukkeansvarlig', 'Lukkeansvarlig');
INSERT INTO roles (id, name) VALUES ('lager', 'Lagermedarbejder');
INSERT INTO roles (id, name) VALUES ('kasse', 'Kassemedarbejder');
INSERT INTO roles (id, name) VALUES ('have', 'Haveansvarlig');

INSERT INTO constraints (id, data) VALUES ('kasse_min_all', '{"id":"kasse_min_all","type":"min_employees","area":"kasse","description":"Mindst 4 medarbejdere i Kasse hele dagen","days":["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],"time_from":"07:00","time_to":"19:00","min_count":4}');
INSERT INTO constraints (id, data) VALUES ('bolig_min_day', '{"id":"bolig_min_day","type":"min_employees","area":"bolig","description":"Mindst 4 medarbejdere i Bolig kl. 07-15","days":["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],"time_from":"07:00","time_to":"15:00","min_count":4}');
INSERT INTO constraints (id, data) VALUES ('bolig_min_evening', '{"id":"bolig_min_evening","type":"min_employees","area":"bolig","description":"Mindst 2 medarbejdere i Bolig efter kl. 15","days":["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],"time_from":"15:00","time_to":"19:00","min_count":2}');
INSERT INTO constraints (id, data) VALUES ('have_min_day', '{"id":"have_min_day","type":"min_employees","area":"have","description":"Mindst 4 medarbejdere i Have kl. 07-15","days":["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],"time_from":"07:00","time_to":"15:00","min_count":4}');
INSERT INTO constraints (id, data) VALUES ('have_min_evening', '{"id":"have_min_evening","type":"min_employees","area":"have","description":"Mindst 2 medarbejdere i Have efter kl. 15","days":["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],"time_from":"15:00","time_to":"19:00","min_count":2}');

INSERT INTO config (key, value) VALUES ('global', '{"opening_hours":{"monday":{"from":"07:00","to":"19:00"},"tuesday":{"from":"07:00","to":"19:00"},"wednesday":{"from":"07:00","to":"19:00"},"thursday":{"from":"07:00","to":"19:00"},"friday":{"from":"07:00","to":"19:00"},"saturday":{"from":"07:00","to":"19:00"},"sunday":{"from":"07:00","to":"19:00"}},"time_slot_minutes":120,"defaults":{"max_hours_per_week":37,"max_hours_per_day":8},"planning":{"max_consecutive_days":6,"min_rest_hours_between_days":11},"closing":{"require_closing_responsible":true,"closing_role":"lukkeansvarlig"},"weekend_days":["saturday","sunday"]}');
